# Generated by Django 3.1.6 on 2021-04-07 00:24
import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Checker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField(max_length=50, unique=True)),
                (
                    "denylist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "severity",
                    models.TextField(
                        choices=[("low", "Low"), ("high", "High")],
                        default="low",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("ignored", "Ignored"),
                            ("succeeding", "Succeeding"),
                            ("failing", "Failing"),
                            ("errored", "Errored"),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                ("latest_status_change", models.DateTimeField(null=True)),
            ],
            options={"ordering": ("-creation_date",)},
        ),
        migrations.CreateModel(
            name="CheckerRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("errored", "Errored"),
                        ],
                        default="succeeded",
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(null=True)),
                (
                    "checker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="checker.checker",
                    ),
                ),
            ],
            options={"ordering": ("-creation_date",)},
        ),
        migrations.CreateModel(
            name="CheckerFailure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("subtext", models.CharField(blank=True, default="", max_length=500)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(null=True)),
                (
                    "checker_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="checker.checkerrun",
                    ),
                ),
            ],
            options={"ordering": ("-creation_date",)},
        ),
    ]
