# Generated by Django 4.0.8 on 2023-09-23 16:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("checker", "0001_initial"),
        ("checker", "0002_checker_latest_run_date"),
        ("checker", "0003_checker_section"),
        ("checker", "0004_checker_description"),
        ("checker", "0005_auto_20210613_2200"),
        ("checker", "0006_auto_20210906_0115"),
        ("checker", "0007_checker_cadence"),
        ("checker", "0008_checkerstatustransition"),
        ("checker", "0009_alter_checker_cadence"),
        ("checker", "0010_alter_checkerstatustransition_creation_date"),
        ("checker", "0011_alter_checker_denylist"),
        ("checker", "0012_auto_20220322_1841"),
        ("checker", "0013_checkeroverride"),
        ("checker", "0014_remove_checker_denylist"),
        ("checker", "0015_alter_checker_options"),
        ("checker", "0016_checkeroverride_apply_to_all_checkers"),
        ("checker", "0017_alter_checkeroverride_checker"),
        ("checker", "0018_checker_user"),
        ("checker", "0019_alter_checkerfailure_subtext"),
        ("checker", "0020_checkeroverride_user"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Checker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField(max_length=50, unique=True)),
                (
                    "severity",
                    models.TextField(
                        choices=[("low", "Low"), ("high", "High")],
                        default="low",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("ignored", "Ignored"),
                            ("succeeding", "Succeeding"),
                            ("failing", "Failing"),
                            ("errored", "Errored"),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                ("latest_status_change", models.DateTimeField(null=True)),
                ("latest_run_date", models.DateTimeField(null=True)),
                ("section", models.TextField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True, max_length=5000)),
                (
                    "cadence",
                    models.TextField(
                        choices=[
                            ("every_ten_minutes", "Every Ten Minutes"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                        ],
                        default="hourly",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CheckerRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("errored", "Errored"),
                        ],
                        default="succeeded",
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(null=True)),
                (
                    "checker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="checker.checker",
                    ),
                ),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-creation_date",),
            },
        ),
        migrations.CreateModel(
            name="CheckerStatusTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "old_value",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("ignored", "Ignored"),
                            ("succeeding", "Succeeding"),
                            ("failing", "Failing"),
                            ("errored", "Errored"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("ignored", "Ignored"),
                            ("succeeding", "Succeeding"),
                            ("failing", "Failing"),
                            ("errored", "Errored"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_transitions",
                        to="checker.checker",
                    ),
                ),
            ],
            options={
                "get_latest_by": "creation_date",
                "ordering": ("creation_date",),
            },
        ),
        migrations.CreateModel(
            name="CheckerFailure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("subtext", models.TextField(blank=True, default="")),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(null=True)),
                (
                    "checker_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="checker.checkerrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-creation_date",),
            },
        ),
        migrations.CreateModel(
            name="CheckerOverride",
            fields=[
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField(null=True)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                (
                    "checker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="checker.checker",
                    ),
                ),
                ("apply_to_all_checkers", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checker_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-creation_date",),
            },
        ),
    ]
