# Generated by Django 3.1.6 on 2021-04-09 20:12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("checker", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="checker",
            name="latest_run_date",
            field=models.DateTimeField(null=True),
        )
    ]
