# Generated by Django 3.1.6 on 2021-04-10 19:30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("checker", "0002_checker_latest_run_date")]

    operations = [
        migrations.AddField(
            model_name="checker",
            name="section",
            field=models.TextField(blank=True, max_length=50),
        )
    ]
