# Generated by Django 3.1.6 on 2021-04-25 23:48
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("checker", "0003_checker_section")]

    operations = [
        migrations.AddField(
            model_name="checker",
            name="description",
            field=models.TextField(blank=True, max_length=5000),
        )
    ]
