# Generated by Django 3.1.10 on 2021-06-13 22:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0004_checker_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkerfailure",
            name="subtext",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
    ]
