# Generated by Django 3.2.4 on 2021-09-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0005_auto_20210613_2200"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkerrun",
            name="completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="checkerrun",
            name="status",
            field=models.TextField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("errored", "Errored"),
                ],
                default="succeeded",
                max_length=50,
            ),
        ),
    ]
