# Generated by Django 3.2.4 on 2021-09-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0006_auto_20210906_0115"),
    ]

    operations = [
        migrations.AddField(
            model_name="checker",
            name="cadence",
            field=models.TextField(
                choices=[("hourly", "Hourly"), ("daily", "Daily")],
                default="hourly",
                max_length=50,
            ),
        ),
    ]
