# Generated by Django 3.2.10 on 2021-12-20 23:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0007_checker_cadence"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckerStatusTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creation_date", models.DateTimeField()),
                (
                    "old_value",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("ignored", "Ignored"),
                            ("succeeding", "Succeeding"),
                            ("failing", "Failing"),
                            ("errored", "Errored"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        choices=[
                            ("new", "New"),
                            ("ignored", "Ignored"),
                            ("succeeding", "Succeeding"),
                            ("failing", "Failing"),
                            ("errored", "Errored"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "checker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_transitions",
                        to="checker.checker",
                    ),
                ),
            ],
        ),
    ]
