# Generated by Django 3.2.10 on 2021-12-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0008_checkerstatustransition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checker",
            name="cadence",
            field=models.TextField(
                choices=[
                    ("every_ten_minutes", "Every Ten Minutes"),
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                ],
                default="hourly",
                max_length=50,
            ),
        ),
    ]
