# Generated by Django 3.2.11 on 2022-02-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0009_alter_checker_cadence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkerstatustransition",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
