# Generated by Django 3.2.11 on 2022-02-16 01:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0010_alter_checkerstatustransition_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checker",
            name="denylist",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(), blank=True, null=True, size=None
            ),
        ),
    ]
