# Generated by Django 3.2.12 on 2022-03-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0011_alter_checker_denylist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkerstatustransition",
            options={"get_latest_by": "creation_date", "ordering": ("creation_date",)},
        ),
        migrations.RenameField(
            model_name="checkerstatustransition",
            old_name="checker",
            new_name="parent",
        ),
        migrations.AlterField(
            model_name="checkerstatustransition",
            name="old_value",
            field=models.TextField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("ignored", "Ignored"),
                    ("succeeding", "Succeeding"),
                    ("failing", "Failing"),
                    ("errored", "Errored"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
