# Generated by Django 3.2.12 on 2022-04-24 20:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0012_auto_20220322_1841"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckerOverride",
            fields=[
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField(null=True)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                (
                    "checker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="checker.checker",
                    ),
                ),
            ],
            options={
                "ordering": ("-creation_date",),
            },
        ),
    ]
