# Generated by Django 3.2.12 on 2022-04-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0013_checkeroverride"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checker",
            name="denylist",
        ),
    ]
