# Generated by Django 3.2.13 on 2022-05-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0014_remove_checker_denylist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checker",
            options={"ordering": ("name",)},
        ),
    ]
