# Generated by Django 4.0.6 on 2022-07-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0015_alter_checker_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkeroverride",
            name="apply_to_all_checkers",
            field=models.BooleanField(default=False),
        ),
    ]
