# Generated by Django 4.0.6 on 2022-07-28 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0016_checkeroverride_apply_to_all_checkers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkeroverride",
            name="checker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overrides",
                to="checker.checker",
            ),
        ),
    ]
