# Generated by Django 4.0.8 on 2023-01-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0018_checker_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkerfailure",
            name="subtext",
            field=models.TextField(blank=True, default=""),
        ),
    ]
