# Generated by Django 4.0.8 on 2023-07-18 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checker", "0019_alter_checkerfailure_subtext"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkeroverride",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checker_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
